version: 2
updates:
  - package-ecosystem: pip
    directory: /qbittorrent-plugin-sync
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:30"
      timezone: Europe/London
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
