---
- hosts: tower
  gather_facts: True
  become_user: {{ userBox }}
  become: yes

  tasks:
    - name: Install EPEL Repository
      yum:
        name: epel-release
        state: present

    - name: Install Ansible
      yum:
        name: ansible
        state: present

    - name: Download Ansible Tower
      get_url:
        url: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
        dest: /tmp/ansible-tower-setup-latest.tar.gz

    - name: Extract Ansible Tower
      unarchive:
        src: /tmp/ansible-tower-setup-latest.tar.gz
        dest: /opt
        remote_src: yes

    - name: Run the Ansible Tower Setup
      shell: |
        cd /opt/ansible-tower-setup-*/
        ./setup.sh
      args:
        creates: /opt/ansible-tower-setup-*/scripts
